### ISSUE TITLE
404 Link - Contributing Guide

### ISSUE THREAD

**Issue by jmpurtle** [marrow/mongo#21]
On this page: https://mongo.webcore.io/installation.html

You have a link towards the bottom for the contributing guide. If clicked, this attempts to take you to https://mongo.webcore.io/CONTRIBUTING.md which appears to hang indefinitely by the spinning icon at the top of the page. In the javascript console, you get 
GET https://mongo.webcore.io/CONTRIBUTING.md 404 ()

**Comment by amcgregor** [comment]
Hard refresh;
