### ISSUE TITLE
Attributes are not working in mixins

### ISSUE THREAD

**Issue by yasek** [marrow/mongo#44]
Subj, I'm trying to implement mixin kind-of 
```
class Complainable(object):
    complainer = ReferenceField('...')
```
And use it like
```
class SomeObj(Complainable, Document):
    ...
```
Then I try to create query object:
```
SomeObj.complainer == ObjectId()
```
I'll get error `'Reference' object has no attribute '__name__'`

**Comment by amcgregor** [comment]
Howdy again!  :)

For mix-ins to work correctly they must share the same metaclass as `Document`.  The easiest way to do this is to have your mix-in subclass `Document`.  The built-in "traits" (which are just mix-ins) do this.

**Comment by yasek** [comment]
Thank you, subclassing Document directly fixed my issue.

**Comment by amcgregor** [comment]
It never hurts to help.  If you have quick questions in the future don't hesitate to pop into #webcore on irc.freenode.net some time.  I'm usually around.  :)
